name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        
      - name: Run glados
        env:
          COOKIE: ${{ secrets.COOKIE }}
        run: dart bin/glados.dart

      - name: Run winxin group
        run: dart bin/weidu.dart
        
      
